### ISSUE TITLE
Constructors not accessible in the REPL

### ISSUE THREAD

**Issue by atennapel** [mmcqd/datatt#1]
I am not able to write `tt` and `ff` in a REPL session. Is this on purpose? It is unexpected for me at least.
```
~/git/datatt/library (main)$ ../_build/default/src/repl.exe
-- data Bool => | tt | ff
data Bool

-- tt
Type Error: 1.1-1.3 - Unbound var `tt`
-- ff
Type Error: 1.1-1.3 - Unbound var `ff`
```

**Comment by mmcqd** [comment]
Yes this is on purpose. Constructors can be overloaded/reused, so they can't have their type synthesized, only checked. Consider
```
data Unit => tt
data Bool => tt | ff
def x => tt
```
What type should `x` have? It's unclear. Instead you'd have to write
```
def x : Unit => tt
```
or
```
def x : Bool => tt
```
Agda actually does exactly the same thing, except it has a special case where the type of a constructor can be inferred if it appears in only one datatype declaration. This could be added, but I don't think it's a big deal.

**Comment by atennapel** [comment]
Ah thanks, that explains it.
