### ISSUE TITLE
Ill-typed normalized output in combination with lifting

### ISSUE THREAD

**Issue by atennapel** [mmcqd/datatt#2]
Lifting is removed (or is it hidden?) in the normalized output in the REPL. Here the output is ill-typed.
```
-- List Type
Type Error: 1.6-1.10 - Type too large to be contained in Type
-- List^1 Type
_ : Type^1

_ = List Type
```

**Comment by mmcqd** [comment]
It's not removed, but the fact that the type was lifted is basically syntactically forgotten, as a consequence of how I implement lifting (which I think is probably kind of weird/questionable). The lift is an unusual term constructor, in that nothing ever gets quoted back into normalized form containing a lift. The level of the datatype and its parameters is higher, but the pretty printer doesn't know that they were originally lower, so it just prints `List`. Potentially the pretty printer could just always print the universe level of datatypes, though then if you declared a type in `Type^1` it would always look lifted.
