### ISSUE TITLE
Lifting should also lift datatypes

### ISSUE THREAD

**Issue by atennapel** [mmcqd/datatt#3]
Currently `lift` only increase the level of universes, but this results in the following ill-typed lifting:
```
-- map^1
_ : (A : Type^1) → (B : Type^1) → (f : A → B) → List A → List B

_ = λ A ⇒ λ B ⇒ λ f ⇒ λ \95 ⇒ elim \95 with | cons x (xs / ih) ⇒ cons (f x) ih | nil ⇒ nil
```
Here `List` is applied to `A`, but `A` is in `Type^1` while `List` expects a `Type`, so this is ill-typed.

I would expect:
```
(A : Type^1) → (B : Type^1) → (f : A → B) → List^1 A → List^1 B
```

**Comment by mmcqd** [comment]
It actually does lift the datatype, see my reply to your other issue. You're right that this output is confusing though.

**Comment by atennapel** [comment]
Could you point me to where in the code the datatype gets lifted? I'm trying to understand your implementation. I found (in `syntax.ml`):
```
let lift i = bottom_up (function 
  | U (Const j) -> U (Const (j + i)) 
  | x -> x)
```
But this only lifts universes.

**Comment by mmcqd** [comment]
Hmmm actually yeah, datatypes in `Syntax` don't actually have their universe level stored syntactically. The way type lifting gets enforced on datatypes is that they have an eta-expanded version of their type constructor in their description (`tm` and `tp` in `Domain.desc`), and this is what actually gets lifted. I say eta-expanded but if the datatype has no parameters then `tm` won't be a function, of course. See what happens in `Nbe.eval` when evaluating a `Lift`. I think this is probably a pretty weird way to have implemented this haha.

**Comment by atennapel** [comment]
Ah that's interesting. Definitely not how I expected it to be implemented :)
